version: '3.8'

volumes:
  vol-redis:

networks:
  net-redis:
    driver: bridge

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - net-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - vol-redis:/data

  redis-commander:
    container_name: rediscommander
    image: rediscommander/redis-commander:latest
    restart: always    
    ports:
      - 8084:8081
    networks:
      - net-redis
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=q1w2e3r4